#!/bin/bash
# =============================================================================
# Syne Setup Script — Run ONCE on first install
# =============================================================================
# This script generates unique database credentials for security.
# It should only be run on fresh installations, not existing ones.
# =============================================================================

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${GREEN}═══════════════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}                    Syne Security Setup                         ${NC}"
echo -e "${GREEN}═══════════════════════════════════════════════════════════════${NC}"
echo

# Check if this is a fresh install or existing
if [ -f ".env" ]; then
    echo -e "${YELLOW}WARNING: .env file already exists.${NC}"
    echo "This script is intended for fresh installations only."
    echo
    read -p "Do you want to regenerate credentials? This will reset the database! (y/N): " confirm
    if [[ ! "$confirm" =~ ^[Yy]$ ]]; then
        echo "Aborted. Keeping existing configuration."
        exit 0
    fi
    echo
    echo -e "${YELLOW}Creating backup of existing .env...${NC}"
    cp .env ".env.backup.$(date +%Y%m%d_%H%M%S)"
fi

# Generate random credentials
echo "🔐 Generating unique database credentials..."

# Generate random username (syne_ + 9 alphanumeric chars)
DB_USER="syne_$(cat /dev/urandom | tr -dc 'a-z0-9' | head -c 9)"

# Generate random password (32 char base64 URL-safe)
DB_PASS="$(openssl rand -base64 32 | tr -d '=/+' | head -c 32)"

# Database name (keep simple)
DB_NAME="syne"

echo "   User: $DB_USER"
echo "   Password: [hidden]"
echo "   Database: $DB_NAME"
echo

# Write .env for the application
echo "📝 Writing .env..."
cat > .env << EOF
# Syne Configuration
# Generated by syne-setup.sh on $(date -Iseconds)
# ─────────────────────────────────────────────────────────────────
# SECURITY: Credentials are now stored in the database after first run.
# This file only needs the database connection URL.
# ─────────────────────────────────────────────────────────────────

SYNE_DATABASE_URL=postgresql://${DB_USER}:${DB_PASS}@localhost:5433/${DB_NAME}

# These are used by docker-compose to create the database
SYNE_DB_USER=${DB_USER}
SYNE_DB_PASSWORD=${DB_PASS}
SYNE_DB_NAME=${DB_NAME}

# ─────────────────────────────────────────────────────────────────
# MIGRATION NOTE: If you have an existing bot token, add it here
# temporarily. Syne will migrate it to the database on first run
# and you should then REMOVE it from this file.
# ─────────────────────────────────────────────────────────────────
# SYNE_TELEGRAM_BOT_TOKEN=your_token_here

EOF

# Set restrictive permissions on .env
chmod 600 .env

echo -e "${GREEN}✅ Configuration generated successfully!${NC}"
echo
echo "Next steps:"
echo "  1. Start the database: docker-compose up -d db"
echo "  2. Start Syne: python -m syne.main (or via systemd)"
echo
echo -e "${YELLOW}IMPORTANT:${NC}"
echo "  - Keep your .env file secure (it contains the database password)"
echo "  - After migrating credentials to DB, remove sensitive values from .env"
echo "  - Never commit .env to version control"
echo

# Check if Docker is running
if command -v docker &> /dev/null; then
    if docker info &> /dev/null; then
        echo -e "${GREEN}Docker is running.${NC}"
        read -p "Start the database container now? (Y/n): " start_db
        if [[ ! "$start_db" =~ ^[Nn]$ ]]; then
            echo "Starting database..."
            docker-compose up -d db
            echo
            echo "Waiting for database to be ready..."
            sleep 5
            echo -e "${GREEN}Database started!${NC}"
        fi
    else
        echo -e "${YELLOW}Docker is installed but not running. Start Docker and run:${NC}"
        echo "  docker-compose up -d db"
    fi
else
    echo -e "${YELLOW}Docker not found. Install Docker and run:${NC}"
    echo "  docker-compose up -d db"
fi

echo
echo -e "${GREEN}Setup complete!${NC}"
